export const users = [
  {
    username: 'user1',
    email: 'user1@gmail.com',
    password: 'pass1',
    // posts: { create: ,},
  }, {
    username: 'user2',
    email: 'user2@gmail.com',
    password: 'pass2',

  }, {
    username: 'user3',
    email: 'user3@gmail.com',
    password: 'pass3',
  },
]

export const topics = [
  { name: "Practice Drawing the Human Figure" },
  { name: "Space" },
  { name: "Still Life" },
  { name: "Draw Facial Expressions" },
  { name: "Monster" },
  { name: "Unusual Environment" },
  { name: "Practice Drawing Interesting Poses" },
  { name: "Draw your Favorite Animal" },
  { name: "Design a Cartoon Character" },
]

export const tags = [
  // Medium
  {
    name: "Digital Art",
    slug: "digital",
  },
  {
    name: "Traditional Mediums",
    slug: "traditional",
  },
  // Type
  {
    name: "Drawing",
    slug: "drawing",
  },
  {
    name: "Painting",
    slug: "painting",
  },
  {
    name: "Sketch",
    slug: "sketch",
  },
  {
    name: "Design",
    slug: "design",
  },
  {
    name: "Illustration",
    slug: "illustration",
  },
  // Style
  {
    name: "Stylized",
    slug: "stylized",
  },
  {
    name: "Realism",
    slug: "realism",
  },
  // Subject Matter
  {
    name: "Characters",
    slug: "characters",
  },
  {
    name: "Creatures",
    slug: "creatures",
  },
  {
    name: "Portrait",
    slug: "portrait",
  },
  {
    name: "Human Figure",
    slug: "figure",
  },
  {
    name: "Environment",
    slug: "environment",
  },
  {
    name: "Architectural",
    slug: "architectural",
  },
  {
    name: "Interior",
    slug: "interior",
  },
  {
    name: "Landscape",
    slug: "landscape",
  },
  {
    name: "Still Life",
    slug: "still-life",
  },
  {
    name: "Props",
    slug: "props",
  },
  {
    name: "Vehicles",
    slug: "vehicles",
  },
  {
    name: "Hard Surface",
    slug: "hard-surface",
  },
  // Genre
  {
    name: "Fantasy",
    slug: "fantasy",
  },
  {
    name: "Sci Fi",
    slug: "sci-fi",
  },
  {
    name: "Fan Art",
    slug: "fan-art",
  },
]


export const posts = [
  {
    title: 'Microscope',
    body: 'Just a drawing of a microscope.',
    images: { create: [{ name: "microscope", url: "seedimages/microscope.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "still-life" } },
  },
  {
    title: 'Alien',
    body: 'Alien from Rick and Morty.',
    images: { create: [{ name: "alien", url: "seedimages/alien.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "space" } },
  },
  {
    title: 'Assassin',
    body: 'On a mission.',
    images: { create: [{ name: "assassin", url: "seedimages/assassin.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: 'Bee',
    body: 'Buzzzz!',
    images: { create: [{ name: "bee", url: "seedimages/bee.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-your-favorite-animal" } },
  },
  {
    title: 'Mushroom Building',
    body: 'Aliens live in it.',
    images: { create: [{ name: "building", url: "seedimages/building.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "unusual-environment" } },
  },
  {
    title: 'Cart',
    body: 'Just an old cart.',
    images: { create: [{ name: "cart", url: "seedimages/cart.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "still-life" } },
  },
  {
    title: 'Cathedral',
    body: 'Cathedral in the cliffs.',
    images: { create: [{ name: "cathedral", url: "seedimages/cathedral.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "unusual-environment" } },
  },
  {
    title: 'Cartoon Characters',
    body: 'Somec artoon characters for my Sci Fi comics.',
    images: { create: [{ name: "chars1", url: "seedimages/chars1.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: 'Chief',
    body: 'Looking at his lands.',
    images: { create: [{ name: "chief", url: "seedimages/chief.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: 'Cowboy',
    body: 'Smug and happy.',
    images: { create: [{ name: "cowboy", url: "seedimages/cowboy.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: 'Passionate Dance',
    body: "They're so in love =)",
    images: { create: [{ name: "dance", url: "seedimages/dance.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-interesting-poses" } },
  },
  {
    title: 'The Devil',
    body: 'Spooky, right?',
    images: { create: [{ name: "devil", url: "seedimages/devil.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "monster" } },
  },
  {
    title: "Dinosaur",
    body: "An adorable dinosaur.",
    images: { create: [{ name: "dinosaur", url: "seedimages/dinosaur.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-your-favorite-animal" } },
  },
  {
    title: "Egg",
    body: "Just a silly egg.",
    images: { create: [{ name: "egg", url: "seedimages/egg.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "monster" } },
  },
  {
    title: "Cartoon faces",
    body: "Kinda goofy but fun",
    images: { create: [{ name: "expressions1", url: "seedimages/expressions1.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-facial-expressions" } },
  },
  {
    title: "Some more Character Expressions",
    body: "I hope you like it!",
    images: { create: [{ name: "expressions2", url: "seedimages/expressions2.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-facial-expressions" } },
  },
  {
    title: "Goofy Faces",
    body: "That was fun to draw!",
    images: { create: [{ name: "expressions3", url: "seedimages/expressions3.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-facial-expressions" } },
  },
  {
    title: "Fallout",
    body: "Ocean after apocalypse",
    images: { create: [{ name: "fallout", url: "seedimages/fallout.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "unusual-environment" } },
  },
  {
    title: "Figures",
    body: "Drawing human figures",
    images: { create: [{ name: "figure1", url: "seedimages/figure1.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-the-human-figure" } },
  },
  {
    title: "More Figures",
    body: "Drawing human figures",
    images: { create: [{ name: "figure2", url: "seedimages/figure2.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-the-human-figure" } },
  },
  {
    title: "Even Figures",
    body: "Drawing human figures",
    images: { create: [{ name: "figure3", url: "seedimages/figure3.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-the-human-figure" } },
  },
  {
    title: "Cartoon Guy",
    body: "Just a cartoon face",
    images: { create: [{ name: "guy1", url: "seedimages/guy1.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: "Cartoon Guy 2",
    body: "Just a cartoon face",
    images: { create: [{ name: "guy2", url: "seedimages/guy2.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: "Cartoon Guy 3",
    body: "Just a cartoon face",
    images: { create: [{ name: "guy3", url: "seedimages/guy3.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: "Cartoon Guy 4",
    body: "Just a cartoon face",
    images: { create: [{ name: "guy4", url: "seedimages/guy4.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  },
  {
    title: "Halloween",
    body: "Sooky!",
    images: { create: [{ name: "halloween", url: "seedimages/halloween.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "monster" } },
  },
  {
    title: "Jedi",
    body: "Warrior vs the Beast.",
    images: { create: [{ name: "jedi", url: "seedimages/jedi.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "monster" } },
  },
  {
    title: "Lindsay",
    body: "My favorite character from freaks and geeks",
    images: { create: [{ name: "lindsay", url: "seedimages/lindsay.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  }, 
  {
    title: "Monster",
    body: "Happy monster",
    images: { create: [{ name: "monster1", url: "seedimages/monster1.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "monster" } },
  }, 
  {
    title: "Octopus",
    body: "Eight legs, zero problems",
    images: { create: [{ name: "octopus", url: "seedimages/octopus.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-your-favorite-animal" } },
  }, 
  {
    title: "Penguin",
    body: "Skiing penguin, no big deal",
    images: { create: [{ name: "penguin", url: "seedimages/penguin.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-your-favorite-animal" } },
  }, 
  {
    title: "Portrait",
    body: "Painted a portrait",
    images: { create: [{ name: "portrait", url: "seedimages/portrait.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-facial-expressions" } },
  }, 
  {
    title: "Cartoon Character Poses 1",
    body: "Just practicing drawing cool poses",
    images: { create: [{ name: "poses1", url: "seedimages/poses1.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-interesting-poses" } },
  }, 
  {
    title: "Cartoon Character Poses 2",
    body: "Just practicing drawing cool poses",
    images: { create: [{ name: "poses2", url: "seedimages/poses2.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-interesting-poses" } },
  },  
  {
    title: "Cartoon Character Poses 4",
    body: "Just practicing drawing cool poses",
    images: { create: [{ name: "poses4", url: "seedimages/poses4.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-interesting-poses" } },
  }, 
  {
    title: "Punk",
    body: "Design a cartoon character",
    images: { create: [{ name: "punk", url: "seedimages/punk.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character"} },
  }, 
  {
    title: "Rat",
    body: "Adorable rat",
    images: { create: [{ name: "rat", url: "seedimages/rat.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-your-favorite-animal" } },
  }, 
  {
    title: "Robot",
    body: "Cool robot",
    images: { create: [{ name: "robot", url: "seedimages/robot.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "space" } },
  }, 
  {
    title: "Scientist Lady",
    body: "Portrait drawing practice",
    images: { create: [{ name: "scientist", url: "seedimages/scientist.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "draw-facial-expressions" } },
  }, 
  {
    title: "Seasons",
    body: "Seasons",
    images: { create: [{ name: "seasons", url: "seedimages/seasons.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "unusual-environment" } },
  }, 
  {
    title: "Shamans",
    body: "Performing some kind of ritual.",
    images: { create: [{ name: "shamans", url: "seedimages/shamans.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "practice-drawing-interesting-poses" } },
  }, 
  {
    title: "Skulls",
    body: "Still life with skulls",
    images: { create: [{ name: "skulls", url: "seedimages/skulls.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "still-life" } },
  }, 
  {
    title: "Space Warrior",
    body: "Here to kick ass and chew bubble gum",
    images: { create: [{ name: "space-warrior", url: "seedimages/space-warrior.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "space" } },
  }, 
  {
    title: "Space",
    body: "Pretty proud of this one",
    images: { create: [{ name: "space", url: "seedimages/space.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "space" } },
  }, 
  {
    title: "Spaceship",
    body: "Inspired by firefly",
    images: { create: [{ name: "spaceship", url: "seedimages/spaceship.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "space" } },
  }, 
  {
    title: "Still Life with Pitcher",
    body: "Still Life with Pitcher",
    images: { create: [{ name: "stilllife", url: "seedimages/stilllife.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "still-life" } },
  }, 
  {
    title: "Utah Teapot",
    body: "I love 3D =)",
    images: { create: [{ name: "teapot", url: "seedimages/teapot.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "still-life" } },
  }, 
  {
    title: "Cartoon Character 1",
    body: "Cartoon Character 1",
    images: { create: [{ name: "toon1", url: "seedimages/toon1.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  }, 
  {
    title: "Cartoon Character 2",
    body: "Cartoon Character 2",
    images: { create: [{ name: "toon2", url: "seedimages/toon2.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  }, 
  {
    title: "Spy",
    body: "Looks shady.",
    images: { create: [{ name: "toon3", url: "seedimages/toon3.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  }, 
  {
    title: "Cartoon Character 4",
    body: "Cartoon Character 4",
    images: { create: [{ name: "toon4", url: "seedimages/toon4.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  }, 
  {
    title: "Lawyer",
    body: "Is on the case.",
    images: { create: [{ name: "toon4", url: "seedimages/toon4.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "design-a-cartoon-character" } },
  }, 
  {
    title: "Turtle",
    body: "Carnivorous turtle =)",
    images: { create: [{ name: "turtle", url: "seedimages/turtle.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "monster" } },
  }, 
  {
    title: "Zombie",
    body: "Brraaaaaiiins!",
    images: { create: [{ name: "zombie", url: "seedimages/zombie.webp" }], },
    tags: { connect: [{ id: "digital" }, { id: "drawing" },] },
    topic: { connect: { id: "monster" } },
  }
]

